
//----------------------------------------------------
// The following code was generated by CUP v0.11a beta 20060608
// Fri Feb 11 13:35:59 CST 2022
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int COMA = 2;
  public static final int DCM = 5;
  public static final int NUMBER = 11;
  public static final int CM = 6;
  public static final int EOF = 0;
  public static final int KM = 10;
  public static final int HM = 9;
  public static final int M = 7;
  public static final int error = 1;
  public static final int PUNTOCOMA = 3;
  public static final int DCAM = 8;
  public static final int MM = 4;
}

